### PR TITLE
Fixes a warning

### PR DESCRIPTION
**Pull request by gmosx**
Fixes a `.characters` warning.

### CODE REVIEW

**Comment by tunniclm** [comment]
~~IIRC this is a breaking change for Swift 4.0 so we should increment the version appropriately when merged.~~
After a quick check, this does not seem to be the case.  My bad,

**Review by tunniclm — APPROVED** [review]

**Comment by tunniclm** [comment]
@gmosx Would you mind registering on the CLA tool, then I will merge this now the Travis tests have completed.

**Comment by gmosx** [comment]
What is the CLA 'tool' ? Link ?
Or should I just scan the CLA Form and email it?

**Comment by gmosx** [comment]
OK I signed it through cla-assistant.io

**Comment by tunniclm** [comment]
@gmosx Well, I can see you are registered on cla-assistant even though the check on PR doesn't seem to have updated properly (even though I tried to get it to be.) So merging.

**Comment by tunniclm** [comment]
Thanks for the fix, sorry it took so long to merge!

**Comment by gmosx** [comment]
Thanks.

**Comment by ianpartridge** [comment]
@tunniclm are you going to tag `2.0.1`?

**Pull request merged**
